version: '3.7'

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: ["yarn", "start:dev"]
    healthcheck:
      test: ["CMD", "node","healthcheck.js"]
      interval: 10s
      timeout: 20s
      retries: 5

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=2I2K4Bbqp1aRhHD8D2ItP80dEGX_NUzkfPHZyGtAJtHPKJvJ
    ports:
      - 4040:4040
    depends_on:
      # - api
      api:
        condition: service_healthy
    command: [ "http", "api:3000" ]
    healthcheck:
      test: /bin/bash -c "</dev/tcp/ngrok/4040"
      interval: 10s
      timeout: 20s
      retries: 5

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-u","user","-ppassword"]
      interval: 10s
      timeout: 20s
      retries: 5

volumes:
  mysql_db: